-- Firebird: list columns on goods receipt tables (run in isql or FlameRobin).
SELECT TRIM(rf.RDB$FIELD_NAME) AS COL_NAME
FROM RDB$RELATION_FIELDS rf
WHERE rf.RDB$RELATION_NAME = 'PH_GR'
ORDER BY rf.RDB$FIELD_POSITION;

SELECT TRIM(rf.RDB$FIELD_NAME) AS COL_NAME
FROM RDB$RELATION_FIELDS rf
WHERE rf.RDB$RELATION_NAME = 'PH_GRDTL'
ORDER BY rf.RDB$FIELD_POSITION;

-- Sample header rows:
-- SELECT FIRST 5 DOCKEY, DOCNO, DOCDATE, DOCAMT FROM PH_GR ORDER BY DOCDATE DESC;

-- Sample lines (replace :docKey):
-- SELECT FIRST 20 * FROM PH_GRDTL WHERE DOCKEY = :docKey ORDER BY SEQ;
